import {test,expect,type Page} from '@playwright/test';
async function ready(page:Page){await page.goto('/');await expect(page.locator('#runtime-status')).toHaveText('SIMULATION ONLINE');}
async function point(page:Page,x:number,y:number){const p=await page.evaluate(([x,y])=>(window as any).fieldworks.screen(x,y),[x,y]);await page.mouse.click(p.x,p.y);}
async function snapshot(page:Page){return page.evaluate(()=>(window as any).fieldworks.snapshot());}
async function buildBranches(page:Page){await page.getByRole('button',{name:'Build Phase tuner',exact:true}).click();await point(page,17.1,12.1);await page.getByRole('button',{name:'Build Field emitter',exact:true}).click();await point(page,20.1,12.1);await page.locator('#tool-field').click();await point(page,16,10.4);await point(page,17,12.5);await point(page,19,12.5);await point(page,20,13.5);await page.locator('#tool-select').click();await point(page,18,12.5);}
test('first outpost can be built, tuned, commissioned, saved and reset through UI',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await ready(page);await page.screenshot({path:'test-results/initial-outpost.png',fullPage:true});
 await expect.poll(async()=>(await snapshot(page)).produced).toBeGreaterThan(0);
 await buildBranches(page);expect((await snapshot(page)).entities.filter((e:any)=>e.kind==='emitter')).toHaveLength(2);expect((await snapshot(page)).links.filter((l:any)=>l.type==='field')).toHaveLength(5);
 await expect(page.locator('#phase')).toBeVisible();const values:number[]=[];for(const phase of [-180,-90,0,90,180]){await page.locator('#phase').evaluate((el,value)=>{(el as HTMLInputElement).value=String(value);el.dispatchEvent(new Event('input',{bubbles:true}));},phase);values.push(await page.evaluate(()=>(window as any).fieldworks.stats().targetPower));}expect(Math.max(...values)-Math.min(...values)).toBeGreaterThan(20);
 await page.locator('#controller').check();await page.locator('#speed').click();await page.locator('#speed').click();await expect.poll(async()=>(await snapshot(page)).frontier,{timeout:45000}).toBe(true);
 await page.locator('#commission').click();await expect.poll(async()=>(await snapshot(page)).commission.state,{timeout:15000}).toBe('qualified');await page.locator('#capture').click();expect((await snapshot(page)).blueprint).not.toBeNull();
 await page.screenshot({path:'test-results/qualified-outpost.png',fullPage:true});
 await page.getByRole('button',{name:'Pause simulation',exact:true}).click();const saved=await snapshot(page);await page.locator('#save').click();await page.locator('#reset').click();await page.locator('#confirm-new').click();expect((await snapshot(page)).frontier).toBe(false);await page.locator('#load').click();const loaded=await snapshot(page);expect(loaded.frontier).toBe(true);expect(loaded.entities).toHaveLength(saved.entities.length);expect(loaded.commission.state).toBe('idle');expect(loaded.blueprint).not.toBeNull();expect(errors).toEqual([]);
});
test('invalid placement is non-destructive, route disconnection works, and manual is usable',async({page})=>{await ready(page);await page.getByRole('button',{name:'Pause simulation',exact:true}).click();const before=await snapshot(page);await page.getByRole('button',{name:'Build Field emitter',exact:true}).click();await point(page,10.1,9.1);await expect(page.locator('#toast')).toContainText('occupied');expect((await snapshot(page)).stock.assemblies).toBe(before.stock.assemblies);await page.keyboard.press('Escape');await point(page,10.5,9.5);await page.locator('[data-disconnect]').first().click();expect((await snapshot(page)).links).toHaveLength(before.links.length-1);await page.locator('#help').click();await expect(page.getByRole('dialog')).toBeVisible();await page.locator('#start-playing').click();await expect(page.getByRole('dialog')).toBeHidden();await page.setViewportSize({width:1024,height:768});await page.screenshot({path:'test-results/compact-outpost.png',fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);});
