import './style.css';
import {loadSprites,spriteUrls} from './assets';
import {Renderer,type View} from './renderer';
import {createWorld,DEFS,DT,step,entity,place,connect,disconnect,setPhase,remove,repair,setController,beginCommission,cancelCommission,captureBlueprint,stampBlueprint,blueprintCost,serialize,deserialize,evaluate,invalidate,type Kind,type World} from './sim/world';

let world=createWorld();let paused=false,speed=1,toastUntil=0,selectedCache='';
const view:View={selected:null,build:null,tool:'select',pending:null,overlay:true,grid:true,mouse:null,panX:25,panY:24,zoom:1};
const $=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
const icon=(name:string)=>`<span class="symbol" aria-hidden="true">${({power:'ϟ',field:'◉',material:'⇢',inspect:'⌖',blueprint:'▧'} as Record<string,string>)[name]??'·'}</span>`;
const fmt=(n:number)=>n.toFixed(1);
document.querySelector('#app')!.innerHTML=`
<header><div class="brand"><span class="brandmark">F<span>↗</span></span><div>FIELDWORKS<small>EXPEDITION / 001</small></div></div><div class="heading"><span class="eyebrow">THE FIRST FRONTIER</span><span>Turn power into precision.</span></div><nav aria-label="Session"><button id="help">Field manual <kbd>?</kbd></button><button id="save">Save</button><button id="load">Load</button><button id="reset" class="quiet">New expedition</button></nav></header>
<section class="resource-bar" aria-label="Factory resources"><div><span class="eyebrow">CONSTRUCTION STOCK</span><strong id="assemblies">28 <small>assemblies</small></strong></div><div><span class="eyebrow">MANUFACTURED</span><strong id="produced">0 <small>total</small></strong></div><div><span class="eyebrow">POWER BUS</span><strong id="power">0 / 240 <small>units</small></strong></div><div><span class="eyebrow">ON TARGET</span><strong id="target">0 <small>field units</small></strong></div><div><span class="eyebrow">FRONTIER CRYSTAL</span><strong id="crystal">0 <small>stored</small></strong></div><div class="time-controls"><button id="pause" aria-label="Pause simulation">Ⅱ</button><button id="speed" aria-label="Simulation speed">1×</button><span id="clock">00:00</span></div></section>
<main><section class="world-panel"><div class="map-toolbar"><div class="tools" aria-label="Map tools"><button id="tool-select" class="active">${icon('inspect')}Inspect</button><button id="tool-field">${icon('field')}Field link</button><button id="tool-material">${icon('material')}Material route</button><button id="tool-blueprint">${icon('blueprint')}Blueprint</button></div><div class="tools"><button id="overlay" class="active">Field view</button><button id="grid" class="active">Grid</button><button id="home" title="Recenter map">⌂</button></div></div><div class="canvas-wrap"><canvas id="world" aria-label="Factory map. Choose a building, then click a grid location. Use field ports to connect machines." tabindex="0"></canvas><div id="map-hint">Inspect equipment or choose a building below.</div><div id="toast" role="status" aria-live="polite"></div><div class="map-legend"><span><i class="line cyan"></i>Field route</span><span><i class="line gold"></i>Material route</span><span>Scroll to zoom · drag with middle mouse</span></div></div><div class="build-dock"><div class="dock-heading"><span class="eyebrow">BUILD OUTPOST</span><span>Choose equipment · click terrain · Esc to cancel</span></div><div id="build-palette"></div></div></section>
<aside><section class="mission"><div class="section-label">01 / FIELD OBJECTIVE<span id="mission-status">IN PROGRESS</span></div><h1>Open the frontier.</h1><p>More emitters give you power.<br>Correct phase puts it where it matters.</p><ol id="objectives"></ol><div class="target-meter"><div><span id="target-label">Armor remaining</span><strong id="armor">600</strong></div><progress id="armor-bar" max="600" value="600"></progress><small>Damage begins above 32 field units on target.</small></div></section>
<section class="inspector"><div class="section-label">02 / EQUIPMENT INSPECTOR</div><div id="inspector"></div></section>
<section class="commission-panel"><div class="section-label">03 / COMMISSIONING</div><label class="switch"><input id="controller" type="checkbox">Automatic phase control</label><p id="commission-reason">Clear the frontier to unlock the acceptance test.</p><progress id="commission-progress" max="20" value="0"></progress><div class="button-row"><button id="commission">Run acceptance test</button><button id="cancel-test" hidden>Cancel</button></div><button id="capture" class="wide" disabled>Record qualified blueprint</button><small id="blueprint-info">A blueprint preserves equipment and internal routes.</small></section>
<section class="ledger"><div class="section-label">04 / ENERGY ACCOUNTING</div><div id="ledger"></div></section><section class="event-log"><div class="section-label">EXPEDITION LOG</div><div id="events"></div></section></aside></main>
<footer><span><b class="online-dot"></b><span id="runtime-status">LOADING ASSETS</span></span><span>FIELDWORKS / FRONTIER EXPERIMENT <span class="version">v0.1</span></span><button id="footer-help" class="footer-help">Field manual ↗</button></footer>
<dialog id="manual"><div class="dialog-header"><span class="eyebrow">EXPEDITION FIELD MANUAL</span><button id="close-help" aria-label="Close manual">×</button></div><h2>Your first coherent outpost</h2><ol><li>Your extractor feeds the assembler along the gold route. Assemblies enter the construction stock automatically.</li><li>Build a <b>phase tuner at (17, 12)</b> and a <b>second emitter at (20, 12)</b>. These are suggested locations; other layouts work.</li><li>Choose <b>Field link</b>. Connect the junction’s lower-right <b>D</b> port to tuner <b>IN</b>, then tuner <b>OUT</b> to the second emitter <b>IN</b>.</li><li>Select the tuner and adjust its phase. Watch <b>On target</b>, not just source power. Unused energy remains visible in the energy ledger.</li><li>Deliver more than <b>32 units</b> to damage the armored organism. Enable automatic control to track thermal drift, or tune manually.</li><li>Once the frontier opens, run the <b>20-second acceptance test</b>. Record a qualified blueprint; after accumulating its cost, place it on the remote ore patch near <b>(38, 3)</b>.</li></ol><h3>Controls & physical model</h3><p>Esc / right click: cancel tool. Space: pause. F: field view. Mouse wheel: zoom. Middle mouse or Alt-drag: pan. Arrow keys: pan. Home: recenter. Click a machine to inspect ports, disconnect routes, repair, or recover equipment.</p><p>Power units supply a local expedition bus within 16 tiles. Fuel and bus wiring are abstracted. Field routes use a narrowband scattering-network solver with compressed phase-per-tile units. Beams and focus rings are diagnostic graphics; the target uses a bounded spatial-mode projection, not a full diffraction calculation.</p><p>Protection reflects incident field upstream at 85°C. Bypassing protection can destroy equipment above 105°C. An intact machine refunds its assembly cost when recovered; buffered ore becomes scrap. Saves restore the installation but require requalification.</p><button id="start-playing" class="primary wide">Return to the outpost</button></dialog>
<dialog id="confirm-reset"><h2>Start a new expedition?</h2><p>This replaces the running outpost. Your manual save remains available.</p><div class="button-row"><button id="confirm-new" class="danger">Start new expedition</button><button id="cancel-new">Keep playing</button></div></dialog>`;
const canvas=$<HTMLCanvasElement>('world'),renderer=new Renderer(canvas,view);
const palette=$('build-palette');
const order:Kind[]=['extractor','assembler','generator','reference','junction','tuner','emitter','dump'];
palette.innerHTML=order.map((kind,i)=>`<button class="build-card" data-build="${kind}" title="${DEFS[kind].description}" aria-label="Build ${DEFS[kind].name}"><span class="build-key">${i+1}</span><img src="${spriteUrls[DEFS[kind].asset]}" alt=""><span>${DEFS[kind].name}</span><small>${DEFS[kind].cost} assemblies</small></button>`).join('');
function toast(text:string){$('toast').textContent=text;toastUntil=performance.now()+4500;$('toast').classList.add('visible');}
function action(error:string){if(error)toast(error);evaluate(world);renderUI(true);}
function setTool(tool:View['tool'],build:Kind|null=null){view.tool=tool;view.build=build;view.pending=null;renderUI(true);}
palette.addEventListener('click',e=>{const button=(e.target as Element).closest<HTMLButtonElement>('[data-build]');if(button)setTool('select',button.dataset.build as Kind);});
for(const tool of ['select','field','material','blueprint'] as const)$(`tool-${tool}`).onclick=()=>{if(tool==='blueprint'&&!world.blueprint){toast('Commission and record a blueprint first');return;}setTool(tool);};
$('overlay').onclick=()=>{view.overlay=!view.overlay;renderUI();};$('grid').onclick=()=>{view.grid=!view.grid;renderUI();};
function home(){view.panX=25;view.panY=24;view.zoom=1;renderer.resize();}
$('home').onclick=home;
$('pause').onclick=()=>{paused=!paused;renderUI();};$('speed').onclick=()=>{speed=speed===1?2:speed===2?4:1;renderUI();};
const storageKey='fieldworks.save.v1';
$('save').onclick=()=>{try{localStorage.setItem(storageKey,serialize(world));toast('Expedition saved locally');}catch{toast('Save failed: browser storage is unavailable or full');}};
$('load').onclick=()=>{try{const raw=localStorage.getItem(storageKey);if(!raw){toast('No saved expedition yet');return;}world=deserialize(raw);view.selected=null;selectedCache='';setTool('select');toast('Save restored. Recommission to verify the installation.');}catch(err){toast(`Load failed: ${err instanceof Error?err.message:'invalid save'}`);}};
$('reset').onclick=()=>{$<HTMLDialogElement>('confirm-reset').showModal();};$('cancel-new').onclick=()=>$<HTMLDialogElement>('confirm-reset').close();$('confirm-new').onclick=()=>{world=createWorld();view.selected=null;selectedCache='';paused=false;speed=1;home();setTool('select');$<HTMLDialogElement>('confirm-reset').close();toast('New expedition started');};
$('footer-help').onclick=$('help').onclick=()=>$<HTMLDialogElement>('manual').showModal();$('close-help').onclick=$('start-playing').onclick=()=>$<HTMLDialogElement>('manual').close();
$<HTMLInputElement>('controller').onchange=e=>{setController(world,(e.target as HTMLInputElement).checked);action('');};
$('commission').onclick=()=>action(beginCommission(world));$('cancel-test').onclick=()=>{cancelCommission(world);renderUI();};$('capture').onclick=()=>action(captureBlueprint(world));
let drag:{x:number;y:number;panX:number;panY:number}|null=null;
function mouse(e:PointerEvent|WheelEvent){const r=canvas.getBoundingClientRect();return renderer.world(e.clientX-r.left,e.clientY-r.top);}
canvas.addEventListener('pointermove',e=>{view.mouse=mouse(e);if(drag){view.panX=drag.panX+e.clientX-drag.x;view.panY=drag.panY+e.clientY-drag.y;}updateHint();});
canvas.addEventListener('pointerleave',()=>{if(!drag)view.mouse=null;});
canvas.addEventListener('pointerdown',e=>{canvas.focus();if(e.button===1||(e.button===0&&e.altKey)){e.preventDefault();drag={x:e.clientX,y:e.clientY,panX:view.panX,panY:view.panY};canvas.setPointerCapture(e.pointerId);return;}if(e.button!==0)return;const p=mouse(e);view.mouse=p;
 if(view.build){const err=place(world,view.build,Math.floor(p.x),Math.floor(p.y));if(!err)view.selected=world.entities.at(-1)!.id;action(err);return;}
 if(view.tool==='blueprint'){action(stampBlueprint(world,Math.floor(p.x),Math.floor(p.y)));return;}
 if(view.tool==='field'){const port=renderer.hitPort(world,p.x,p.y);if(!port){toast('Click a circular field port, not the machine body');return;}if(!view.pending){view.pending=port;view.selected=port.node;toast('Choose the destination port');}else{const err=connect(world,'field',view.pending,port);if(!err)view.pending=null;action(err);}renderUI(true);return;}
 const hit=renderer.hit(world,p.x,p.y);
 if(view.tool==='material'){if(!hit){toast('Choose an extractor, then an assembler');return;}if(!view.pending){if(hit.kind!=='extractor'){toast('Start the material route at an extractor');return;}view.pending={node:hit.id,port:0};toast('Now choose the destination assembler');}else{const err=connect(world,'material',view.pending,{node:hit.id,port:0});if(!err)view.pending=null;action(err);}return;}
 view.selected=hit?.id??null;renderUI(true);
});
canvas.addEventListener('pointerup',e=>{drag=null;if(canvas.hasPointerCapture(e.pointerId))canvas.releasePointerCapture(e.pointerId);});canvas.addEventListener('pointercancel',()=>{drag=null;});
canvas.addEventListener('contextmenu',e=>{e.preventDefault();setTool('select');});
canvas.addEventListener('wheel',e=>{e.preventDefault();const rect=canvas.getBoundingClientRect(),sx=e.clientX-rect.left,sy=e.clientY-rect.top,before=renderer.world(sx,sy);view.zoom=Math.max(.55,Math.min(2.4,view.zoom*Math.exp(-e.deltaY*.001)));renderer.resize();view.panX=sx-before.x*renderer.scale;view.panY=sy-before.y*renderer.scale;},{passive:false});
window.addEventListener('resize',()=>renderer.resize());
window.addEventListener('keydown',e=>{if(e.target instanceof HTMLInputElement||document.querySelector('dialog[open]'))return;if(e.code==='Space'){e.preventDefault();paused=!paused;renderUI();}if(e.key==='Escape')setTool('select');if(e.key.toLowerCase()==='f'){view.overlay=!view.overlay;renderUI();}if(e.key==='?')$<HTMLDialogElement>('manual').showModal();if(e.key==='Home')home();if(e.key==='ArrowLeft')view.panX+=50;if(e.key==='ArrowRight')view.panX-=50;if(e.key==='ArrowUp')view.panY+=50;if(e.key==='ArrowDown')view.panY-=50;if(/^[1-8]$/.test(e.key))setTool('select',order[Number(e.key)-1]);});
function updateHint(){const p=view.mouse;const coord=p?` / ${Math.floor(p.x)}, ${Math.floor(p.y)}`:'';const text=view.build?`Place ${DEFS[view.build].name} · ${DEFS[view.build].cost} assemblies`:view.tool==='field'?(view.pending?'Choose destination port':'Choose source field port'):view.tool==='material'?(view.pending?'Choose destination assembler':'Choose source extractor'):view.tool==='blueprint'?`Place recorded outpost · ${blueprintCost(world)} assemblies`:'Inspect equipment · ? for field manual';$('map-hint').textContent=text+coord;}
function row(label:string,value:string,cls=''){return `<div class="stat-row"><span>${label}</span><strong class="${cls}">${value}</strong></div>`;}
function renderInspector(force=false){const e=view.selected?entity(world,view.selected):undefined;const cache=e?`${e.id}/${world.links.length}/${e.kind}`:'none';const rebuild=force||cache!==selectedCache;selectedCache=cache;
 if(!e){if(rebuild)$('inspector').innerHTML='<div class="empty-inspector"><span>⌖</span><h3>Select a machine</h3><p>Inspect its field ports, temperature, and production. Select a tuner to adjust phase.</p></div>';return;}
 if(rebuild){const d=DEFS[e.kind];$('inspector').innerHTML=`<div class="equipment-title"><img src="${spriteUrls[d.asset]}" alt=""><div><h2>${d.name}</h2><small>${e.id.toUpperCase()} / ${e.x}, ${e.y}</small></div></div><p>${d.description}</p><div id="equipment-stats"></div>${e.kind==='tuner'?'<label class="phase-label" for="phase">Relative phase <output id="phase-value"></output></label><input id="phase" type="range" min="-180" max="180" step="1"><div class="range-labels"><span>−180°</span><span>0°</span><span>+180°</span></div>':''}<div id="port-stats"></div><div class="route-list">${world.links.filter(l=>l.a.node===e.id||l.b.node===e.id).map(l=>`<div><span>${l.type==='field'?'◉':'⇢'} ${l.a.node} → ${l.b.node}</span><button data-disconnect="${l.id}" aria-label="Disconnect route ${l.id}">Disconnect</button></div>`).join('')}</div><label class="switch"><input id="protection" type="checkbox" ${e.protection?'checked':''}>Thermal protection</label><div class="button-row"><button id="repair">Repair · 3</button><button id="recover" class="quiet">${e.health>0?'Recover equipment':'Clear wreck'}</button></div>`;
  const phase=$<HTMLInputElement>('phase');if(phase){phase.value=String(e.phase);phase.oninput=()=>{setPhase(world,e.id,Number(phase.value));evaluate(world);renderUI();};}
  $('repair').onclick=()=>action(repair(world,e.id));$('recover').onclick=()=>{remove(world,e.id);view.selected=null;action('');};$<HTMLInputElement>('protection').onchange=ev=>{e.protection=(ev.target as HTMLInputElement).checked;invalidate(world,'Protection setting changed');if(!e.protection)toast('Protection bypassed: overheating can destroy equipment');renderUI();};
  $('inspector').querySelectorAll<HTMLButtonElement>('[data-disconnect]').forEach(b=>b.onclick=()=>{disconnect(world,b.dataset.disconnect!);action('');});
 }
 $('equipment-stats').innerHTML=row('State',e.health<=0?'Destroyed':e.tripped?'Tripped':e.powered?'Operating':'No power',e.powered?'green':'amber')+row('Temperature',`${fmt(e.temperature)} °C`,e.temperature>85?'red':'')+row('Integrity',`${Math.ceil(e.health)}%`)+((e.kind==='extractor'||e.kind==='assembler')?row('Ore buffer',`${e.ore} / 20`):'');
 if(e.kind==='tuner'){$('phase-value').textContent=`${fmt(e.phase)}°`;$<HTMLInputElement>('phase').value=String(e.phase);}
 $('port-stats').innerHTML=DEFS[e.kind].ports.map((name,i)=>{const p=world.stats.network.ports[e.id]?.[i];return `<div class="port-readout"><b>${name}</b><span>in ${fmt(p?.incoming??0)}</span><span>out ${fmt(p?.outgoing??0)}</span></div>`;}).join('');
}
function renderUI(force=false){const s=world.stats;$('assemblies').innerHTML=`${world.stock.assemblies}<small>assemblies</small>`;$('produced').innerHTML=`${world.produced}<small>total</small>`;$('power').innerHTML=`${s.demand} / ${s.supply}<small>units</small>`;$('target').innerHTML=`${fmt(s.targetPower)}<small>field units</small>`;$('target').classList.toggle('green',s.targetPower>=32);$('crystal').innerHTML=`${world.stock.crystal}<small>stored</small>`;
 const mins=Math.floor(world.time/60),seconds=Math.floor(world.time%60);$('clock').textContent=`${String(mins).padStart(2,'0')}:${String(seconds).padStart(2,'0')}`;$('pause').textContent=paused?'▶':'Ⅱ';$('pause').setAttribute('aria-label',paused?'Resume simulation':'Pause simulation');$('speed').textContent=`${speed}×`;
 const steps=[{done:world.produced>0,title:'Automate component production',sub:'Extractor → assembler → construction stock'},{done:world.entities.filter(e=>e.kind==='emitter').length>=2&&world.entities.some(e=>e.kind==='tuner'),title:'Extend the field network',sub:'Build a tuner + second emitter. Link junction D → tuner → emitter.'},{done:world.frontier,title:'Concentrate power on the target',sub:'Tune relative phase. Hold more than 32 units to break the armor.'},{done:world.commission.state==='qualified',title:'Commission a reusable outpost',sub:'Enable control, pass the drift test, record a blueprint.'}];$('objectives').innerHTML=steps.map((v,i)=>`<li class="${v.done?'done':''}"><b>${v.done?'✓':String(i+1).padStart(2,'0')}</b><div><strong>${v.title}</strong><small>${v.sub}</small></div></li>`).join('');$('mission-status').textContent=world.commission.state==='qualified'?'QUALIFIED':world.frontier?'FRONTIER OPEN':'IN PROGRESS';$('armor').textContent=world.frontier?'CLEARED':String(Math.ceil(world.target.health));$<HTMLProgressElement>('armor-bar').value=world.target.health;
 $<HTMLInputElement>('controller').checked=world.controller;const test=world.commission;$('commission-reason').textContent=world.frontier?`${test.reason}${test.state==='qualified'?` · ${fmt(test.rating)} units`:''}`:'Clear the frontier to unlock the acceptance test.';$<HTMLProgressElement>('commission-progress').value=test.elapsed;$<HTMLButtonElement>('commission').disabled=!world.frontier||test.state==='testing';$('cancel-test').hidden=test.state!=='testing';$<HTMLButtonElement>('capture').disabled=test.state!=='qualified';$('blueprint-info').textContent=world.blueprint?`Recorded · ${blueprintCost(world)} assemblies · ${world.blueprint.width} × ${world.blueprint.height} tiles`:'A blueprint preserves equipment and internal routes.';
 $('ledger').innerHTML=row('Source field',`${fmt(s.network.sourcePower)}`)+row('On target',fmt(s.targetPower),'green')+row('Off target',fmt(s.offTarget))+row('Heat',fmt(s.heat))+row('Open ports + route loss',fmt(s.network.escaped+s.network.linkLoss),'amber')+row('Balance error',Math.abs(s.network.residual)<1e-6?'≤ 0.000001':fmt(s.network.residual))+row('Scrapped material',String(world.stock.scrap));
 $('events').innerHTML=world.events.slice(0,4).map(e=>`<p><time>${Math.floor(e.time/60)}:${String(Math.floor(e.time%60)).padStart(2,'0')}</time>${e.text}</p>`).join('');
 for(const tool of ['select','field','material','blueprint'])$(`tool-${tool}`).classList.toggle('active',view.tool===tool&&!view.build);$('overlay').classList.toggle('active',view.overlay);$('grid').classList.toggle('active',view.grid);palette.querySelectorAll<HTMLButtonElement>('[data-build]').forEach(b=>{const k=b.dataset.build as Kind;b.classList.toggle('active',view.build===k);b.classList.toggle('unaffordable',world.stock.assemblies<DEFS[k].cost);});
 $('runtime-status').textContent=s.error?`NETWORK ERROR: ${s.error}`:paused?'SIMULATION PAUSED':'SIMULATION ONLINE';updateHint();renderInspector(force);
}
let previous=performance.now(),accumulator=0,lastUI=0;
function frame(now:number){const elapsed=Math.min(.2,(now-previous)/1000);previous=now;if(!paused&&!document.hidden&&!document.querySelector('dialog[open]')){accumulator+=elapsed*speed;while(accumulator>=DT){step(world);accumulator-=DT;}}else accumulator=0;renderer.draw(world);if(now-lastUI>150){renderUI();lastUI=now;}if(now>toastUntil)$('toast').classList.remove('visible');requestAnimationFrame(frame);}
async function start(){try{await loadSprites();renderer.resize();renderUI(true);requestAnimationFrame(frame);}catch(err){$('runtime-status').textContent='ASSET LOAD FAILED';toast(String(err));}}
// Read-only introspection for browser validation; absent from production builds.
if(import.meta.env.DEV){Object.assign(window,{fieldworks:{snapshot:()=>JSON.parse(serialize(world)),stats:()=>structuredClone(world.stats),screen:(x:number,y:number)=>{const p=renderer.screen(x,y),r=canvas.getBoundingClientRect();return {x:p.x+r.left,y:p.y+r.top};}}});}
start();
