import {type World,type Kind,type Entity,DEFS,WIDTH,HEIGHT,center,portPosition,placementError,entity} from './sim/world';
import type {Endpoint} from './sim/network';
import {sprites} from './assets';
export interface View {selected:string|null;build:Kind|null;tool:'select'|'field'|'material'|'blueprint';pending:Endpoint|null;overlay:boolean;grid:boolean;mouse:{x:number;y:number}|null;panX:number;panY:number;zoom:number}
export class Renderer {
 ctx:CanvasRenderingContext2D; width=0;height=0;scale=30;
 constructor(public canvas:HTMLCanvasElement,public view:View){this.ctx=canvas.getContext('2d')!;this.resize();}
 resize(){const r=this.canvas.getBoundingClientRect();this.width=r.width;this.height=r.height;const d=Math.min(devicePixelRatio,2);this.canvas.width=Math.round(r.width*d);this.canvas.height=Math.round(r.height*d);this.ctx.setTransform(d,0,0,d,0,0);this.scale=Math.max(16,Math.min(this.width/35,this.height/23))*this.view.zoom;}
 screen(x:number,y:number){return{x:x*this.scale+this.view.panX,y:y*this.scale+this.view.panY};}
 world(x:number,y:number){return{x:(x-this.view.panX)/this.scale,y:(y-this.view.panY)/this.scale};}
 hit(w:World,x:number,y:number):Entity|undefined {return [...w.entities].reverse().find(e=>x>=e.x&&x<=e.x+DEFS[e.kind].w&&y>=e.y&&y<=e.y+DEFS[e.kind].h);}
 hitPort(w:World,x:number,y:number):Endpoint|null {let best:Endpoint|null=null,dist=14/this.scale;for(const e of w.entities)DEFS[e.kind].ports.forEach((_,i)=>{const p=portPosition(e,i),d=Math.hypot(x-p.x,y-p.y);if(d<dist){dist=d;best={node:e.id,port:i};}});return best;}
 draw(w:World){const ctx=this.ctx,s=this.scale;ctx.clearRect(0,0,this.width,this.height);ctx.fillStyle='#17282b';ctx.fillRect(0,0,this.width,this.height);
  // Deterministic coarse terrain texture; visual only, never feeds simulation.
  for(let x=0;x<WIDTH;x++)for(let y=0;y<HEIGHT;y++){const p=this.screen(x,y);if(p.x<-s||p.y<-s||p.x>this.width||p.y>this.height)continue;const noise=Math.sin(x*127.1+y*311.7)*43758.5453;ctx.fillStyle=`rgba(145,165,129,${.025+Math.abs(noise%1)*.035})`;ctx.fillRect(p.x,p.y,s,s);if((x*7+y*13)%11===0){ctx.fillStyle='#415352';ctx.fillRect(p.x+s*.2,p.y+s*.6,2,1);}}
  if(this.view.grid){ctx.strokeStyle='#8ba79914';ctx.lineWidth=1;ctx.beginPath();for(let x=0;x<=WIDTH;x++){const a=this.screen(x,0),b=this.screen(x,HEIGHT);ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);}for(let y=0;y<=HEIGHT;y++){const a=this.screen(0,y),b=this.screen(WIDTH,y);ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);}ctx.stroke();}
  for(const dep of w.deposits){this.sprite(dep.kind==='ore'?'starter-ore':'frontier-crystal-ore',dep.x,dep.y,dep.w,dep.h,dep.remaining>0?1:.25);const p=this.screen(dep.x+dep.w/2,dep.y+dep.h+.4);this.label(p.x,p.y,dep.kind==='ore'?'FERROUS DEPOSIT':'PRECISION CRYSTAL',dep.kind==='ore'?'#b5a283':'#95cfde',9);}
  const boundary=this.screen(25,0);ctx.fillStyle=w.frontier?'#b5d8ab05':'#c5a4720b';ctx.fillRect(boundary.x,this.view.panY,WIDTH*s,this.height);ctx.strokeStyle=w.frontier?'#92cc9270':'#bda97566';ctx.setLineDash([5,7]);ctx.beginPath();ctx.moveTo(boundary.x,0);ctx.lineTo(boundary.x,this.height);ctx.stroke();ctx.setLineDash([]);
  for(const l of w.links){const a=entity(w,l.a.node)!,b=entity(w,l.b.node)!;const ap=l.type==='field'?portPosition(a,l.a.port):center(a),bp=l.type==='field'?portPosition(b,l.b.port):center(b);const p=this.screen(ap.x,ap.y),q=this.screen(bp.x,bp.y);const energy=w.stats.network.ports[a.id]?.[l.a.port]?.outgoing??0;const color=l.type==='material'?'#cba75f':this.view.overlay?'#6acecd':'#769495';ctx.strokeStyle='#0d171b';ctx.lineWidth=l.type==='material'?8:6;ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(q.x,q.y);ctx.stroke();ctx.strokeStyle=color;ctx.lineWidth=l.type==='material'?3:this.view.overlay?2+Math.min(2,energy/40):2;ctx.setLineDash(l.type==='material'?[3,4]:[]);ctx.stroke();ctx.setLineDash([]);if(l.type==='material'||this.view.overlay){const t=(w.time*(l.type==='material'?.16:.4))%1;ctx.fillStyle=color;ctx.beginPath();ctx.arc(p.x+(q.x-p.x)*t,p.y+(q.y-p.y)*t,3,0,Math.PI*2);ctx.fill();}}
  if(this.view.overlay){const target=this.screen(w.target.x,w.target.y);for(const e of w.entities.filter(e=>e.kind==='emitter'&&e.powered)){const p=center(e),q=this.screen(p.x,p.y);const power=w.stats.network.ports[e.id]?.[0]?.incoming??0;if(power<.1)continue;ctx.save();ctx.globalCompositeOperation='screen';const g=ctx.createLinearGradient(q.x,q.y,target.x,target.y);g.addColorStop(0,'#7bf2e52c');g.addColorStop(1,'#8bf0d350');ctx.fillStyle=g;ctx.beginPath();ctx.moveTo(q.x,q.y-3);ctx.lineTo(target.x,target.y-12);ctx.lineTo(target.x,target.y+12);ctx.lineTo(q.x,q.y+3);ctx.fill();ctx.strokeStyle='#a2edd594';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(q.x,q.y);ctx.lineTo(target.x,target.y);ctx.stroke();ctx.restore();}}
  if(w.target.health>0)this.sprite('armored-frontier-organism',w.target.x-2,w.target.y-2,4,4);else{const p=this.screen(w.target.x,w.target.y);ctx.strokeStyle='#9fd4ae';ctx.beginPath();ctx.arc(p.x,p.y,25,0,Math.PI*2);ctx.stroke();this.label(p.x,p.y,'CLEARED','#a7d6ae',10);}
  const target=this.screen(w.target.x,w.target.y);if(this.view.overlay){const rad=8+Math.max(0,40-w.stats.targetPower);ctx.strokeStyle='#8ae2cc88';ctx.lineWidth=1.5;ctx.beginPath();ctx.ellipse(target.x,target.y,rad,rad*.6,0,0,Math.PI*2);ctx.stroke();}
  this.label(target.x,target.y+2.6*s,w.frontier?'FRONTIER OPEN':`ARMORED ORGANISM · ${Math.ceil(w.target.health)}`,'#ddd3ae',10);
  for(const e of [...w.entities].sort((a,b)=>a.y-b.y)){const d=DEFS[e.kind],p=this.screen(e.x,e.y);if(p.x+d.w*s<0||p.y+d.h*s<0||p.x>this.width||p.y>this.height)continue;const selected=this.view.selected===e.id;ctx.fillStyle=selected?'#93dec715':'#121d211c';ctx.fillRect(p.x,p.y,d.w*s,d.h*s);if(selected){ctx.strokeStyle='#a8dbc1';ctx.lineWidth=1.5;ctx.strokeRect(p.x-2,p.y-2,d.w*s+4,d.h*s+4);}this.sprite(d.asset,e.x,e.y,d.w,d.h,e.health<=0?.3:e.powered||d.watts===0?1:.55);
   const status=e.health<=0?'WRECK':e.tripped?'TRIPPED':!e.powered&&d.watts?'NO POWER':'';if(status)this.label(p.x+d.w*s/2,p.y-7,status,'#efb07c',9);else{ctx.fillStyle='#b5dd9a';ctx.beginPath();ctx.arc(p.x+d.w*s-3,p.y+5,2.5,0,Math.PI*2);ctx.fill();}
   if(e.temperature>55){ctx.fillStyle='#151b20';ctx.fillRect(p.x,p.y+d.h*s+3,d.w*s,3);ctx.fillStyle=e.temperature>85?'#ed8d70':'#d0ac6a';ctx.fillRect(p.x,p.y+d.h*s+3,d.w*s*Math.min(1,e.temperature/120),3);}
   if(this.view.tool==='field'||selected||this.view.overlay){d.ports.forEach((name,i)=>{const pp=portPosition(e,i),q=this.screen(pp.x,pp.y);const pending=this.view.pending?.node===e.id&&this.view.pending.port===i;ctx.fillStyle=pending?'#f2cb7b':'#193234';ctx.strokeStyle=pending?'#f2cb7b':'#90d8c8';ctx.lineWidth=1.5;ctx.beginPath();ctx.arc(q.x,q.y,this.view.tool==='field'?6:4,0,Math.PI*2);ctx.fill();ctx.stroke();if(this.view.tool==='field'||selected)this.label(q.x+(i<2?-10:10),q.y-8,name,'#caf0da',8);});}
  }
  if(this.view.pending&&this.view.mouse){const e=entity(w,this.view.pending.node);if(e){const p=this.view.tool==='material'?center(e):portPosition(e,this.view.pending.port),a=this.screen(p.x,p.y),b=this.screen(this.view.mouse.x,this.view.mouse.y);ctx.setLineDash([5,5]);ctx.strokeStyle='#dac38b';ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();ctx.setLineDash([]);}}
  if(this.view.build&&this.view.mouse){const x=Math.floor(this.view.mouse.x),y=Math.floor(this.view.mouse.y),d=DEFS[this.view.build],p=this.screen(x,y),bad=placementError(w,this.view.build,x,y);ctx.fillStyle=bad?'#eb7f7225':'#b4e4b320';ctx.strokeStyle=bad?'#ed8d7c':'#c4eac5';ctx.fillRect(p.x,p.y,d.w*s,d.h*s);ctx.strokeRect(p.x,p.y,d.w*s,d.h*s);this.sprite(d.asset,x,y,d.w,d.h,.6);}
  if(this.view.tool==='blueprint'&&this.view.mouse&&w.blueprint){const p=this.screen(Math.floor(this.view.mouse.x),Math.floor(this.view.mouse.y));ctx.strokeStyle='#e9c67d';ctx.setLineDash([6,3]);ctx.strokeRect(p.x,p.y,w.blueprint.width*s,w.blueprint.height*s);ctx.setLineDash([]);}
  ctx.fillStyle='#102024bb';ctx.fillRect(16,this.height-37,305,24);ctx.fillStyle='#9eb7b5';ctx.font='10px monospace';ctx.fillText(`SECTOR 07 / ${w.frontier?'EASTERN ACCESS OPEN':'FRONTIER RESTRICTED'} / ${Math.round(this.view.zoom*100)}%`,26,this.height-21);
 }
 sprite(id:string,x:number,y:number,w:number,h:number,alpha=1){const im=sprites[id];if(!im)return;const p=this.screen(x,y),ctx=this.ctx;const size=Math.max(w,h)*this.scale*1.16;ctx.save();ctx.globalAlpha=alpha;ctx.drawImage(im,p.x+w*this.scale/2-size/2,p.y+h*this.scale/2-size/2,size,size);ctx.restore();}
 label(x:number,y:number,text:string,color:string,size:number){const c=this.ctx;c.font=`${size}px "IBM Plex Mono", monospace`;c.textAlign='center';c.fillStyle='#142124d9';const width=c.measureText(text).width;c.fillRect(x-width/2-4,y-size,width+8,size+5);c.fillStyle=color;c.fillText(text,x,y);c.textAlign='left';}
}
