"""Generate assets/INDEX.md: every asset blend, its ASSET_ collections, size, triangles, accuracy and hooks.

Run: blender -b --python scripts/assets/make_index.py -- assets
"""
import glob, json, os, sys
import bpy

root = sys.argv[sys.argv.index("--") + 1]
rows = []
for jp in sorted(glob.glob(os.path.join(root, "components", "*", "*.json"))):
    cat = os.path.basename(os.path.dirname(jp))
    try:
        meta = json.load(open(jp))
    except Exception as e:
        continue
    bp = jp[:-5] + ".blend"
    if not os.path.exists(bp):
        continue
    with bpy.data.libraries.load(bp) as (src, dst):
        colls = [c for c in src.collections if c.startswith("ASSET_") or c.startswith("VARIANT_")]
        ngs = list(src.node_groups)
    rows.append((cat, os.path.basename(bp), meta, colls, ngs, os.path.getsize(bp)))
out = ["# Asset index", "", "Generated by `scripts/assets/make_index.py`. Units: metres in Blender; sizes in mm.", ""]
cur = None
for cat, fn, meta, colls, ngs, size in rows:
    if cat != cur:
        out += ["", "## " + cat, "", "| blend | collections | size mm | tris | accuracy | hooks | file MB |", "|---|---|---|---|---|---|---|"]
        cur = cat
    sz = meta.get("size_mm")
    hooks = meta.get("hooks")
    if isinstance(hooks, dict):
        hooks = list(hooks.keys())
    names = []
    for h in (hooks or []):
        names.append(h.get("name", str(h)) if isinstance(h, dict) else str(h))
    hk = ", ".join(names[:6]) + (" ..." if len(names) > 6 else "")
    acc = meta.get("accuracy") or meta.get("accuracy_level") or ""
    cl = ", ".join([c.replace("ASSET_", "") for c in colls if c.startswith("ASSET_")][:6])
    out.append("| %s | %s | %s | %s | %s | %s | %.1f |" % (fn, cl, "x".join(str(round(v, 1)) for v in sz) if sz else "", meta.get("triangles", ""), acc, hk, size / 1e6))
open(os.path.join(root, "INDEX.md"), "w").write("\n".join(out) + "\n")
print("INDEX rows", len(rows))
