"""initial_schema

Revision ID: 0faf33ae7a64
Revises: 
Create Date: 2026-04-22 23:51:52.445834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0faf33ae7a64'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('label', sa.String(length=160), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('region', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('address_line', sa.String(length=500), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('location_type', sa.String(length=80), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_locations'))
    )
    op.create_index(op.f('ix_locations_city'), 'locations', ['city'], unique=False)
    op.create_index(op.f('ix_locations_country'), 'locations', ['country'], unique=False)
    op.create_index(op.f('ix_locations_location_type'), 'locations', ['location_type'], unique=False)
    op.create_index(op.f('ix_locations_region'), 'locations', ['region'], unique=False)
    op.create_table('source_links',
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('source_type', sa.String(length=120), nullable=False),
    sa.Column('url_or_reference', sa.String(length=800), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_links'))
    )
    op.create_index(op.f('ix_source_links_entity_id'), 'source_links', ['entity_id'], unique=False)
    op.create_index(op.f('ix_source_links_entity_type'), 'source_links', ['entity_type'], unique=False)
    op.create_index(op.f('ix_source_links_source_type'), 'source_links', ['source_type'], unique=False)
    op.create_table('tags',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('color', sa.String(length=40), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags'))
    )
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_table('users',
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    users_table = sa.table(
        'users',
        sa.column('id', sa.Uuid()),
        sa.column('display_name', sa.String()),
        sa.column('email', sa.String()),
        sa.column('is_default', sa.Boolean()),
    )
    op.bulk_insert(
        users_table,
        [
            {
                'id': '00000000-0000-4000-8000-000000000001',
                'display_name': 'Local User',
                'email': None,
                'is_default': True,
            }
        ],
    )
    op.create_table('entity_locations',
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_entity_locations_location_id_locations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entity_locations'))
    )
    op.create_index(op.f('ix_entity_locations_entity_id'), 'entity_locations', ['entity_id'], unique=False)
    op.create_index(op.f('ix_entity_locations_entity_type'), 'entity_locations', ['entity_type'], unique=False)
    op.create_index(op.f('ix_entity_locations_location_id'), 'entity_locations', ['location_id'], unique=False)
    op.create_table('entity_tags',
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_entity_tags_tag_id_tags'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entity_tags'))
    )
    op.create_index(op.f('ix_entity_tags_entity_id'), 'entity_tags', ['entity_id'], unique=False)
    op.create_index(op.f('ix_entity_tags_entity_type'), 'entity_tags', ['entity_type'], unique=False)
    op.create_index(op.f('ix_entity_tags_tag_id'), 'entity_tags', ['tag_id'], unique=False)
    op.create_table('interaction_events',
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('type', sa.String(length=80), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('context', sa.String(length=240), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('sentiment', sa.String(length=80), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_interaction_events_created_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interaction_events'))
    )
    op.create_index(op.f('ix_interaction_events_context'), 'interaction_events', ['context'], unique=False)
    op.create_index(op.f('ix_interaction_events_deleted_at'), 'interaction_events', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_interaction_events_started_at'), 'interaction_events', ['started_at'], unique=False)
    op.create_index(op.f('ix_interaction_events_title'), 'interaction_events', ['title'], unique=False)
    op.create_index(op.f('ix_interaction_events_type'), 'interaction_events', ['type'], unique=False)
    op.create_table('organizations',
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('type', sa.String(length=80), nullable=False),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('industry', sa.String(length=160), nullable=True),
    sa.Column('location', sa.String(length=240), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_organizations_created_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations'))
    )
    op.create_index(op.f('ix_organizations_deleted_at'), 'organizations', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_organizations_industry'), 'organizations', ['industry'], unique=False)
    op.create_index(op.f('ix_organizations_location'), 'organizations', ['location'], unique=False)
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=False)
    op.create_index(op.f('ix_organizations_type'), 'organizations', ['type'], unique=False)
    op.create_table('people',
    sa.Column('display_name', sa.String(length=240), nullable=False),
    sa.Column('given_name', sa.String(length=120), nullable=True),
    sa.Column('family_name', sa.String(length=120), nullable=True),
    sa.Column('nickname', sa.String(length=120), nullable=True),
    sa.Column('pronouns', sa.String(length=80), nullable=True),
    sa.Column('short_bio', sa.Text(), nullable=True),
    sa.Column('relationship_summary', sa.Text(), nullable=True),
    sa.Column('how_we_met', sa.Text(), nullable=True),
    sa.Column('first_met_date', sa.Date(), nullable=True),
    sa.Column('primary_location', sa.String(length=240), nullable=True),
    sa.Column('relationship_score', sa.Integer(), nullable=False),
    sa.Column('relationship_category', sa.String(length=40), nullable=False),
    sa.Column('last_interaction_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_reminder_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_people_created_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_people'))
    )
    op.create_index(op.f('ix_people_deleted_at'), 'people', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_people_display_name'), 'people', ['display_name'], unique=False)
    op.create_index(op.f('ix_people_primary_location'), 'people', ['primary_location'], unique=False)
    op.create_index(op.f('ix_people_relationship_category'), 'people', ['relationship_category'], unique=False)
    op.create_table('pipelines',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('template_type', sa.String(length=120), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_pipelines_created_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pipelines'))
    )
    op.create_index(op.f('ix_pipelines_name'), 'pipelines', ['name'], unique=False)
    op.create_index(op.f('ix_pipelines_template_type'), 'pipelines', ['template_type'], unique=False)
    op.create_table('reminders',
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('priority', sa.String(length=40), nullable=False),
    sa.Column('snoozed_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('entity_type', sa.String(length=80), nullable=True),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_reminders_created_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reminders'))
    )
    op.create_index(op.f('ix_reminders_deleted_at'), 'reminders', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_reminders_due_at'), 'reminders', ['due_at'], unique=False)
    op.create_index(op.f('ix_reminders_entity_id'), 'reminders', ['entity_id'], unique=False)
    op.create_index(op.f('ix_reminders_entity_type'), 'reminders', ['entity_type'], unique=False)
    op.create_index(op.f('ix_reminders_priority'), 'reminders', ['priority'], unique=False)
    op.create_index(op.f('ix_reminders_snoozed_until'), 'reminders', ['snoozed_until'], unique=False)
    op.create_index(op.f('ix_reminders_status'), 'reminders', ['status'], unique=False)
    op.create_index(op.f('ix_reminders_title'), 'reminders', ['title'], unique=False)
    op.create_table('contact_methods',
    sa.Column('person_id', sa.Uuid(), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('type', sa.String(length=80), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_contact_methods_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], name=op.f('fk_contact_methods_person_id_people'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contact_methods'))
    )
    op.create_index(op.f('ix_contact_methods_organization_id'), 'contact_methods', ['organization_id'], unique=False)
    op.create_index(op.f('ix_contact_methods_person_id'), 'contact_methods', ['person_id'], unique=False)
    op.create_index(op.f('ix_contact_methods_type'), 'contact_methods', ['type'], unique=False)
    op.create_index(op.f('ix_contact_methods_value'), 'contact_methods', ['value'], unique=False)
    op.create_table('event_locations',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['interaction_events.id'], name=op.f('fk_event_locations_event_id_interaction_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_event_locations_location_id_locations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', 'location_id', name=op.f('pk_event_locations'))
    )
    op.create_table('event_organizations',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['interaction_events.id'], name=op.f('fk_event_organizations_event_id_interaction_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_event_organizations_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', 'organization_id', name=op.f('pk_event_organizations'))
    )
    op.create_table('event_people',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['interaction_events.id'], name=op.f('fk_event_people_event_id_interaction_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], name=op.f('fk_event_people_person_id_people'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', 'person_id', name=op.f('pk_event_people'))
    )
    op.create_table('external_profiles',
    sa.Column('person_id', sa.Uuid(), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('platform', sa.String(length=120), nullable=False),
    sa.Column('url_or_handle', sa.String(length=500), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_external_profiles_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], name=op.f('fk_external_profiles_person_id_people'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_external_profiles'))
    )
    op.create_index(op.f('ix_external_profiles_organization_id'), 'external_profiles', ['organization_id'], unique=False)
    op.create_index(op.f('ix_external_profiles_person_id'), 'external_profiles', ['person_id'], unique=False)
    op.create_index(op.f('ix_external_profiles_platform'), 'external_profiles', ['platform'], unique=False)
    op.create_table('person_organizations',
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('role_type', sa.String(length=120), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_person_organizations_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], name=op.f('fk_person_organizations_person_id_people'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_person_organizations'))
    )
    op.create_index(op.f('ix_person_organizations_organization_id'), 'person_organizations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_person_organizations_person_id'), 'person_organizations', ['person_id'], unique=False)
    op.create_index(op.f('ix_person_organizations_role_type'), 'person_organizations', ['role_type'], unique=False)
    op.create_table('pipeline_stages',
    sa.Column('pipeline_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=40), nullable=True),
    sa.Column('is_terminal', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], name=op.f('fk_pipeline_stages_pipeline_id_pipelines'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pipeline_stages'))
    )
    op.create_index(op.f('ix_pipeline_stages_pipeline_id'), 'pipeline_stages', ['pipeline_id'], unique=False)
    op.create_table('pipeline_items',
    sa.Column('pipeline_id', sa.Uuid(), nullable=False),
    sa.Column('stage_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('primary_person_id', sa.Uuid(), nullable=True),
    sa.Column('primary_organization_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('priority', sa.String(length=40), nullable=False),
    sa.Column('expected_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], name=op.f('fk_pipeline_items_pipeline_id_pipelines'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['primary_organization_id'], ['organizations.id'], name=op.f('fk_pipeline_items_primary_organization_id_organizations')),
    sa.ForeignKeyConstraint(['primary_person_id'], ['people.id'], name=op.f('fk_pipeline_items_primary_person_id_people')),
    sa.ForeignKeyConstraint(['stage_id'], ['pipeline_stages.id'], name=op.f('fk_pipeline_items_stage_id_pipeline_stages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pipeline_items'))
    )
    op.create_index(op.f('ix_pipeline_items_pipeline_id'), 'pipeline_items', ['pipeline_id'], unique=False)
    op.create_index(op.f('ix_pipeline_items_primary_organization_id'), 'pipeline_items', ['primary_organization_id'], unique=False)
    op.create_index(op.f('ix_pipeline_items_primary_person_id'), 'pipeline_items', ['primary_person_id'], unique=False)
    op.create_index(op.f('ix_pipeline_items_priority'), 'pipeline_items', ['priority'], unique=False)
    op.create_index(op.f('ix_pipeline_items_stage_id'), 'pipeline_items', ['stage_id'], unique=False)
    op.create_index(op.f('ix_pipeline_items_status'), 'pipeline_items', ['status'], unique=False)
    op.create_index(op.f('ix_pipeline_items_title'), 'pipeline_items', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pipeline_items_title'), table_name='pipeline_items')
    op.drop_index(op.f('ix_pipeline_items_status'), table_name='pipeline_items')
    op.drop_index(op.f('ix_pipeline_items_stage_id'), table_name='pipeline_items')
    op.drop_index(op.f('ix_pipeline_items_priority'), table_name='pipeline_items')
    op.drop_index(op.f('ix_pipeline_items_primary_person_id'), table_name='pipeline_items')
    op.drop_index(op.f('ix_pipeline_items_primary_organization_id'), table_name='pipeline_items')
    op.drop_index(op.f('ix_pipeline_items_pipeline_id'), table_name='pipeline_items')
    op.drop_table('pipeline_items')
    op.drop_index(op.f('ix_pipeline_stages_pipeline_id'), table_name='pipeline_stages')
    op.drop_table('pipeline_stages')
    op.drop_index(op.f('ix_person_organizations_role_type'), table_name='person_organizations')
    op.drop_index(op.f('ix_person_organizations_person_id'), table_name='person_organizations')
    op.drop_index(op.f('ix_person_organizations_organization_id'), table_name='person_organizations')
    op.drop_table('person_organizations')
    op.drop_index(op.f('ix_external_profiles_platform'), table_name='external_profiles')
    op.drop_index(op.f('ix_external_profiles_person_id'), table_name='external_profiles')
    op.drop_index(op.f('ix_external_profiles_organization_id'), table_name='external_profiles')
    op.drop_table('external_profiles')
    op.drop_table('event_people')
    op.drop_table('event_organizations')
    op.drop_table('event_locations')
    op.drop_index(op.f('ix_contact_methods_value'), table_name='contact_methods')
    op.drop_index(op.f('ix_contact_methods_type'), table_name='contact_methods')
    op.drop_index(op.f('ix_contact_methods_person_id'), table_name='contact_methods')
    op.drop_index(op.f('ix_contact_methods_organization_id'), table_name='contact_methods')
    op.drop_table('contact_methods')
    op.drop_index(op.f('ix_reminders_title'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_status'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_snoozed_until'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_priority'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_entity_type'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_entity_id'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_due_at'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_deleted_at'), table_name='reminders')
    op.drop_table('reminders')
    op.drop_index(op.f('ix_pipelines_template_type'), table_name='pipelines')
    op.drop_index(op.f('ix_pipelines_name'), table_name='pipelines')
    op.drop_table('pipelines')
    op.drop_index(op.f('ix_people_relationship_category'), table_name='people')
    op.drop_index(op.f('ix_people_primary_location'), table_name='people')
    op.drop_index(op.f('ix_people_display_name'), table_name='people')
    op.drop_index(op.f('ix_people_deleted_at'), table_name='people')
    op.drop_table('people')
    op.drop_index(op.f('ix_organizations_type'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_location'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_industry'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_deleted_at'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_interaction_events_type'), table_name='interaction_events')
    op.drop_index(op.f('ix_interaction_events_title'), table_name='interaction_events')
    op.drop_index(op.f('ix_interaction_events_started_at'), table_name='interaction_events')
    op.drop_index(op.f('ix_interaction_events_deleted_at'), table_name='interaction_events')
    op.drop_index(op.f('ix_interaction_events_context'), table_name='interaction_events')
    op.drop_table('interaction_events')
    op.drop_index(op.f('ix_entity_tags_tag_id'), table_name='entity_tags')
    op.drop_index(op.f('ix_entity_tags_entity_type'), table_name='entity_tags')
    op.drop_index(op.f('ix_entity_tags_entity_id'), table_name='entity_tags')
    op.drop_table('entity_tags')
    op.drop_index(op.f('ix_entity_locations_location_id'), table_name='entity_locations')
    op.drop_index(op.f('ix_entity_locations_entity_type'), table_name='entity_locations')
    op.drop_index(op.f('ix_entity_locations_entity_id'), table_name='entity_locations')
    op.drop_table('entity_locations')
    op.drop_table('users')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_source_links_source_type'), table_name='source_links')
    op.drop_index(op.f('ix_source_links_entity_type'), table_name='source_links')
    op.drop_index(op.f('ix_source_links_entity_id'), table_name='source_links')
    op.drop_table('source_links')
    op.drop_index(op.f('ix_locations_region'), table_name='locations')
    op.drop_index(op.f('ix_locations_location_type'), table_name='locations')
    op.drop_index(op.f('ix_locations_country'), table_name='locations')
    op.drop_index(op.f('ix_locations_city'), table_name='locations')
    op.drop_table('locations')
    # ### end Alembic commands ###
